stages:
  - code-quality
  - api-tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .pip-cache/
    - ~/.cache/pip
    - ~/.local/lib/python3*/site-packages

code-quality:
  stage: code-quality
  script:
    - python3 -m pip install --user --upgrade pip
    
    - python3 -m pip install --user -r requirements.txt
    
    - echo "Checking code formatting..."
    - python3 -m black . --check || (echo "❌ Code formatting check failed. Run 'black .' locally to fix formatting" && exit 1)
    - cd server
    - python3 manage.py check || (echo "❌ Django system checks failed" && exit 1)
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /(main|develop)/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(main|develop)/

api-tests:
  stage: api-tests
  script:
    # Upgrade pip in user space
    - python3 -m pip install --user --upgrade pip
    
    # Install dependencies
    - python3 -m pip install --user -r requirements.txt
    
    # Run tests
    - cd server
    - python3 manage.py test --verbosity=2
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /(main|develop)/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(main|develop)/