image: python:3.10-slim

stages:
  - code-quality
  - api-tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PATH: "$PATH:/root/.local/bin"  # Add local bin to PATH

cache:
  paths:
    - .pip-cache/
    
before_script:
  - python -m pip install --upgrade pip setuptools wheel

code-quality:
  stage: code-quality
  script:
    # Install dependencies
    - pip install -r requirements.txt
    
    # Code quality checks
    - python -m black . --check || (echo "❌ Code formatting check failed. Run 'black .' locally to fix formatting" && exit 1)
    - python -m isort . --check-only --diff || (echo "❌ Import sorting check failed. Run 'isort .' locally to fix imports" && exit 1)
    - python -m bandit -r . || (echo "❌ Security checks failed. Please review the security issues" && exit 1)
    - python manage.py check || (echo "❌ Django system checks failed" && exit 1)
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /(main|develop)/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(main|develop)/

api-tests:
  stage: api-tests
  variables:
    DJANGO_SETTINGS_MODULE: "skinscan.settings_test"
  script:
    # Install dependencies
    - pip install -r requirements.txt
    
    # Run migrations on test database
    - echo "Setting up test database..."
    - python manage.py migrate
    
    # Run tests
    - echo "Running API tests..."
    - python manage.py test --verbosity=2
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /(main|develop)/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(main|develop)/